### ISSUE TITLE
Fixed plot origin?

### ISSUE THREAD

**Issue by Gasman2014** [yaqwsx/PcbDraw#12] opened 2018-02-26 15:11 UTC
Am trying to plot versions of boards that are in a VCS and then use ImageMagick to identify the differences.  Using your script, I am now able to produce files like these (where green is in the new plot but not the old and red was in the old but not the new).

![diff-74b1-b1d3](https://user-images.githubusercontent.com/8401593/36676986-f54d7494-1b04-11e8-91d1-09fe5c28fd7e.png)
diff-74b1-b1d3

![diff-b1d3-192a](https://user-images.githubusercontent.com/8401593/36677310-ba5f22dc-1b05-11e8-9778-f4aac62da471.png)
diff-b1d-192a

Sometimes, however, the origin of the plot is shifted and I get this effect:

![diff2](https://user-images.githubusercontent.com/8401593/36677029-165b94c2-1b05-11e8-9fea-9354b3087665.png).

Do you know how is the plot origin is set and if it can be fixed? I have had some success by setting the <g transform="translate(-xxxx, -xx)" lines of both plots to the same values but I am unsure as to how the plotting origin is determined. I am also keen to use your xml tree to parse where the diffs have occurred.

**Comment by yaqwsx** [comment] 2018-02-26 15:26
Ok this is strange. The script itself should not move the board substrate in any way.

Could you please try save SVG returned by the get_board_substrate function? If it differs for different version of your board, then the problem is in KiCAD.

Also haven't you added a hidden reference/text/or something outside the board in PcbNew? This could lead to this behaviour.

**Comment by yaqwsx** [comment] 2018-07-18 12:43
Do you have any progress regarding this issue?

**Comment by Gasman2014** [comment] 2018-07-18 13:29
Had rather put this project on hold as I had come up with an alternative plan (but have not yet had sufficient time to implement it).

Since the error was due to an artefact off screen, I am happy for this to be closed.

**Comment by yaqwsx** [comment] 2018-07-18 13:31
Thank you for the clarification. Closing.

**Closed by yaqwsx** 2018-07-18 13:31 UTC
