### ISSUE TITLE
Non-square PCBs are rendered broken

### ISSUE THREAD

**Issue by kb-elmo** [yaqwsx/PcbDraw#96] opened 2022-06-01 07:12 UTC
When trying to render a PCB that is not a simple square and instead has multiple different angled sides PCBdraw renders most of the PCB as a transparent area.

Example:  
![image](https://i.imgur.com/iDYAN15.png)

Rendered file:  
[test_pcb.zip](https://github.com/yaqwsx/PcbDraw/files/8811842/test_pcb.zip)

**Comment by yaqwsx** [comment] 2022-06-01 07:18
I suspect that your outline is not continuous and you have small gaps between the arc.

**Comment by kb-elmo** [comment] 2022-06-01 07:32
Like I said there is no discontinuation.

I added the example file to my original post btw so you can check it yourself if you don't believe me.

![image](https://i.aggressive.pizza/WindowsTerminal_2022-06-01_09-32-16.png)

**Comment by yaqwsx** [comment] 2022-06-02 06:27
Thank you, having the file will help me to trace the bug (I confirm it is there).

**Comment by JordanAceto** [comment] 2022-06-24 02:40
Hello :)

I also have been having some similar issues when the corners are not square. Below is an image of two very similar, but different boards. In an attempt to troubleshoot I copy-pasted the edge-cuts layer from the good board on the right into the bad board the left using `pcb_new`, but the odd behavior persisted.

My system is: KiCad 6.0.6 on Ubuntu 22.04

![left_bad_right_good](https://user-images.githubusercontent.com/29663925/175449092-c369ccd0-8533-492d-967f-1caa90626433.png)

Below is a zip file with two nearly identical minimal boards, as seen above. One of them draws fine and the other has that big weird triangle. Perhaps it can be used as a troubleshooting aid. I was using KiBot when I ran into the issue, and I left some convenience Make and yaml files in there.

[pcbdraw_test.zip](https://github.com/yaqwsx/PcbDraw/files/8972733/pcbdraw_test.zip)

Thanks and all the best.

**Comment by set-soft** [comment] 2022-06-24 12:06
Hi @JordanAceto !

I found the problem and will be fixed in the PcbDraw that I include with KiBot.
The problem is just about the tolerance in the code that joins segments, it was 5 nm and now is 1 µm. The failing case is a 52 nm error in the KiCad SVG generation (rounding issues).
PcbDraw is changing a lot and I'm not sure if I'll be able to use the current git code soon.

**Comment by JordanAceto** [comment] 2022-06-24 13:33
Hi @set-soft, what you wrote makes perfect sense. I confirm that when I apply your patch the left board from my image above prints correctly. Thank you!

**Comment by set-soft** [comment] 2022-06-24 14:28
Hi @JordanAceto and @kb-elmo  !
I added a new release to my fork: https://github.com/INTI-CMNB/PcbDraw/releases/tag/v0.9.0-2 including this patch.
Is also uploaded it to the KiBot Debian/Ubuntu repo:  https://set-soft.github.io/debian/

**Comment by yaqwsx** [comment] 2022-06-26 20:00
The change was applied in 2f50ead

**Closed by yaqwsx** 2022-06-26 20:00 UTC

**Comment by kb-elmo** [comment] 2022-06-26 20:04
Thanks! 😄

**Comment by duckyb** [comment] 2022-08-10 10:30
@yaqwsx would it be possible to include this fix in a new release of kikit docker? I would like to have this fix in my github actions automated workflow.

**Comment by yaqwsx** [comment] 2022-09-26 08:22
Note that v1 was released, which includes proper edges reconstruction. Also, the KiKit docker image already contains this new version.
